### ISSUE TITLE
Improve README installation guide

### ISSUE THREAD

**Issue by Painatalman** [AndyLPK247/pycon-2020-web-app-testing#2]
This is a minor suggestion, but we could **add headings to installation steps for specific OSes**.

This improves both navigation in the README, and it allows linking to those specific sections.

**Comment by Painatalman** [comment]
I proposed my changes in #3. It's just a suggestion, so feel free to close the issue and PR, if you find them inadequate.

**Comment by AndyLPK247** [comment]
Thanks! Great suggestion. I'll make separate commits to include them.

**Comment by AndyLPK247** [comment]
I just committed the changes to _master_ and all the _example_ branches.
